title: Aznor Yusof # your name (or website title) here
logo: "/images/profile_pic.JPG?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  <br>
  Data Scientist with a Master of IT in Business (Artificial Intelligence) from Singapore Management University.
  <br><br>
  Specialises in delivering Data Science solutions across various domains, including Natural Language Processing, Audio Signal Processing, Machine Learning and Recommendation Systems.
  <br><br>
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here

colors:
  crimson: '#900C3F'